version: 2

before:
  hooks:
    - go mod download

builds:
  - main: ./cmd/mcp-helm
    binary: mcp-helm
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^example:'

dockers:
  - image_templates:
      - "ghcr.io/zekker6/mcp-helm:latest-linux-amd64"
      - "ghcr.io/zekker6/mcp-helm:{{ .Tag }}-linux-amd64"
    dockerfile: docker/Dockerfile.goreleaser
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
    goos: linux
    goarch: amd64
  - image_templates:
      - "ghcr.io/zekker6/mcp-helm:latest-linux-arm64"
      - "ghcr.io/zekker6/mcp-helm:{{ .Tag }}-linux-arm64"
    dockerfile: docker/Dockerfile.goreleaser
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
    goos: linux
    goarch: arm64
  - image_templates:
      - "ghcr.io/zekker6/mcp-helm:latest-darwin-amd64"
      - "ghcr.io/zekker6/mcp-helm:{{ .Tag }}-darwin-amd64"
    dockerfile: docker/Dockerfile.goreleaser
    build_flag_templates:
      - "--pull"
      - "--platform=darwin/amd64"
    goos: darwin
    goarch: amd64
  - image_templates:
      - "ghcr.io/zekker6/mcp-helm:latest-darwin-arm64"
      - "ghcr.io/zekker6/mcp-helm:{{ .Tag }}-darwin-arm64"
    dockerfile: docker/Dockerfile.goreleaser
    build_flag_templates:
      - "--pull"
      - "--platform=darwin/arm64"
    goos: darwin
    goarch: arm64

docker_manifests:
  - name_template: "ghcr.io/zekker6/mcp-helm:latest"
    image_templates:
      - "ghcr.io/zekker6/mcp-helm:latest-linux-amd64"
      - "ghcr.io/zekker6/mcp-helm:latest-linux-arm64"
      - "ghcr.io/zekker6/mcp-helm:latest-darwin-amd64"
      - "ghcr.io/zekker6/mcp-helm:latest-darwin-arm64"
  - name_template: "ghcr.io/zekker6/mcp-helm:{{ .Tag }}"
    image_templates:
      - "ghcr.io/zekker6/mcp-helm:{{ .Tag }}-linux-amd64"
      - "ghcr.io/zekker6/mcp-helm:{{ .Tag }}-linux-arm64"
      - "ghcr.io/zekker6/mcp-helm:{{ .Tag }}-darwin-amd64"
      - "ghcr.io/zekker6/mcp-helm:{{ .Tag }}-darwin-arm64"

